# fly.toml app configuration file generated for datingapp777 on 2023-04-19T16:42:28-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "datingapp777"
primary_region = "lax"

[build]
  image = "shin7772/datingapp:latest"

[env]
  ASPNETCORE_URLS="http://+:8080"
  CloudinarySettings__Cloudname="dvzlgazgz"
  CloudinarySettings__ApiKey="228511683156616"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true

[checks]
  [checks.alive]
    type = "tcp"
    interval = "15s"
    timeout = "2s"
    grace_period = "5s"
